# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizePaper', '0002_auto_20170723_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
